# Generated by Django 4.2.7 on 2023-11-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraped',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
