# Generated by Django 4.2.7 on 2023-11-07 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scraped_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraped',
            old_name='author',
            new_name='autor',
        ),
    ]
