# Generated by Django 4.2.7 on 2023-11-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_rename_author_scraped_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlsScraped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='scraped',
            name='urls',
            field=models.ManyToManyField(related_name='scraped', to='scraper.urlsscraped'),
        ),
    ]
